Repository rottingresearch/rottingresearch, pull requests merged in 2022-10, with the labels that each got.

#69 Resolved Fix mobile view #61
  static/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#70 resolved Incomplete URL substring sanitization
  app.py
Labels: hacktoberfest, hacktoberfest-accepted

#71 Url security
  .github/workflows/codeql-analysis.yml
  app.py
Labels: hacktoberfest, hacktoberfest-accepted

#73 Resolved Refactor code & adopt standard code linter #53
  templates/upload.html
Labels: hacktoberfest, Design, Flask, Quality Control, hacktoberfest-accepted

#79 updated homepage styles
  static/css/style.css
  templates/upload.html
Labels: hacktoberfest, Design, frontend, Flask, hacktoberfest-accepted

#80 Logo styles & spacing adjustments
  static/css/style.css
Labels: hacktoberfest, Design, frontend, hacktoberfest-accepted

#81 Update style.css
  static/css/style.css
Labels: hacktoberfest, Design, frontend, hacktoberfest-accepted

#82 Updated styles
  static/css/style.css
Labels: hacktoberfest, Design, frontend, hacktoberfest-accepted

#83 Updated mobile styles of upload form
  static/css/style.css
  templates/upload.html
Labels: hacktoberfest, Design, frontend, hacktoberfest-accepted
